class AppEndPoints {
  static const String baseUrl = 'http://api.finemenu.net/api/';
  static const String category = 'categories';
  static const String item = 'users/1/items';
  static String itemById(int id) => 'items/$id';
  static const String order = 'orders';
  static String restaurantWithId(int id) => 'webapp/restaurant/$id';
  static const String bearerToken =
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiNzU2YTc1YWNiMzY2ZjgyMTJjMmNiOGRjNzVkOGU4MWMwNGQ2NGU5ODk2ZjYxM2M4MjRmZmFiODA0ZmIxODc2MzhlYmI4MmQzYTY3NzYxMDgiLCJpYXQiOjE3MDA5MDAyMzEuNDg5ODk1LCJuYmYiOjE3MDA5MDAyMzEuNDg5OSwiZXhwIjoxNzMyNTIyNjMxLjQ3OTk2Mywic3ViIjoiMSIsInNjb3BlcyI6W119.pi33ecSvv_GcfoNbC9tw29lPPQ7oEpeNNgYCTLOZpe6lhwqPFpwLCrZZXdHDu2P3IO5h7ktLS1wsUVUzVjPmc_ddXjSFDKVzzmguqWzUSSG73xwabLnEL6ulwc6ecuiVCnzKa1RFXFU4bVOA9gAvrWC2K1tzDW8E_KbyRd4Vur4kXIOhpYKytHMBv_fRuvMkbuKEDtDJ7EiOkJxE1BvhyqVAvEcYf8EPcNpQ9UnUP2beXej4CTZG7OA54nTisozw03osLr-SPUa2iWg21rnJStZmIozTtTaw6UdmFRar5_Yi9nUsTboyVEwuXCGdUvGEwn8VXI28xo8prAYC_ohtYMW49DqI8X8Kh_vRmLOIEJRS2ogAObe0PNYdG395bX8lu2tnm8ZR3FDHvi-quJ7cgL6rsSeBh0wjg-IMHCcIiGSLRf6qsqkTFgRSCyR8xFdWYGx_8uHlrZpaHWzDkZ2zGN4hWpFPuc65YuXl4ik95zPBa_PNOScURMIhUuw9K9yKKt15HXuIc-6RqKnT2evXSb2NL_Am4PlUKMlrcoyDevbqHiZoMgeRLCT6KiIzkWdMz10f5l_1r4HBuXQppZZZ02ObgaGQkp5Y1DabvmHtSvZyHW2tFu83ZG3I4YQKEh2zJMQp6vZR7tKrKP8n20wFgmCEgaxCTX6wxiMOtlh6wM4';
}
